# Generated by Django 4.2.1 on 2023-05-25 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_avion', models.CharField(max_length=50)),
                ('Modèle', models.CharField(max_length=50)),
                ('capacité', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_compagnie', models.CharField(max_length=50)),
                ('Nom', models.CharField(max_length=50)),
                ('pays', models.CharField(max_length=50)),
                ('Images', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Portes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num_porte', models.CharField(max_length=50)),
                ('Id_compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aeroport.compagnie')),
            ],
        ),
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_vols', models.CharField(max_length=50)),
                ('Aeroport_depart', models.CharField(max_length=50)),
                ('Aeroport_arrivée', models.CharField(max_length=50)),
                ('Heure_départ', models.TimeField()),
                ('Heure_arrivée', models.TimeField()),
                ('Id_avion', models.CharField(max_length=50)),
                ('Images', models.ImageField(upload_to='')),
                ('Num_porte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aeroport.portes')),
            ],
        ),
        migrations.AddField(
            model_name='portes',
            name='Id_vols',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aeroport.vol'),
        ),
    ]
